# Generated by Django 3.2 on 2022-03-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.AlterField(
            model_name='hscode',
            name='ait',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='atv',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='cd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='rd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='sd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='vat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
