# Generated by Django 3.2 on 2022-03-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='product_name',
            field=models.CharField(max_length=23, null=True),
        ),
    ]
