# Generated by Django 3.2 on 2022-03-08 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220308_0704'),
        ('purchase', '0002_purchaseinvoice_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='product_name',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='address',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='mobile',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='order_deadline',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterModelTable(
            name='purchaseinvoice',
            table=None,
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('raw_material', 'Raw Material'), ('finished_good', 'Finished Good')], max_length=200)),
                ('uom', models.CharField(choices=[('number', 'NMB'), ('kg', 'KGM')], max_length=25)),
                ('cd', models.FloatField(default=0)),
                ('sd', models.FloatField(default=0)),
                ('vat', models.FloatField(default=0)),
                ('ait', models.FloatField(default=0)),
                ('rd', models.FloatField(default=0)),
                ('atv', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('remark', models.CharField(max_length=200)),
                ('pi_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseinvoice')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
        ),
    ]
