# Generated by Django 3.2 on 2022-05-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchaseinvoiceline_hs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='invoice_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
