# Generated by Django 3.2 on 2023-05-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20220514_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoiceline',
            name='ait_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceline',
            name='atv_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceline',
            name='cd_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceline',
            name='rd_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceline',
            name='sd_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceline',
            name='tti',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceline',
            name='tti_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceline',
            name='vat_amount',
        ),
    ]
