# Generated by Django 3.2 on 2023-05-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_auto_20230518_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='total_payable',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='tti',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='tti_amount',
            field=models.FloatField(default=0),
        ),
    ]
