# Generated by Django 3.2 on 2022-03-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=144)),
                ('address', models.TextField(blank=True, null=True)),
                ('Tax_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('mobile', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('is_customer', models.BooleanField(default=0)),
                ('is_vendor', models.BooleanField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
