# Generated by Django 3.2 on 2023-05-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_alter_parties_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
