# Generated by Django 3.2 on 2022-03-13 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('products', '0002_auto_20220308_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=455, null=True)),
                ('order_deadline', models.DateField(auto_now_add=True, null=True)),
                ('mobile', models.CharField(max_length=25, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.parties')),
            ],
        ),
        migrations.CreateModel(
            name='SaleInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=200, null=True)),
                ('product_type', models.CharField(choices=[('raw_material', 'Raw Material'), ('finished_good', 'Finished Good')], max_length=200)),
                ('uom', models.CharField(choices=[('number', 'NMB'), ('kg', 'KGM')], max_length=25)),
                ('cd', models.FloatField(default=0)),
                ('sd', models.FloatField(default=0)),
                ('vat', models.FloatField(default=0)),
                ('ait', models.FloatField(default=0)),
                ('rd', models.FloatField(default=0)),
                ('atv', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('remark', models.CharField(max_length=200)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
                ('si_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.saleinvoice')),
            ],
        ),
    ]
