# Generated by Django 3.2 on 2022-05-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='invoice_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
