# Generated by Django 3.2 on 2022-05-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleinvoice_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoiceline',
            name='cd_amount',
            field=models.FloatField(default=0),
        ),
    ]
