# Generated by Django 3.2 on 2022-05-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20220514_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinvoiceline',
            name='ait_amount',
        ),
        migrations.RemoveField(
            model_name='saleinvoiceline',
            name='atv_amount',
        ),
        migrations.RemoveField(
            model_name='saleinvoiceline',
            name='cd_amount',
        ),
        migrations.RemoveField(
            model_name='saleinvoiceline',
            name='rd_amount',
        ),
        migrations.RemoveField(
            model_name='saleinvoiceline',
            name='sd_amount',
        ),
        migrations.RemoveField(
            model_name='saleinvoiceline',
            name='vat_amount',
        ),
    ]
