# Generated by Django 3.2 on 2023-05-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20220514_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoiceline',
            name='total_payable',
            field=models.FloatField(default=0),
        ),
    ]
